# -*- coding: utf-8 -*-
"""capstone_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/primawn/03ba42ae58b84f154ab1964466e1ab55/capstone_2.ipynb

## Import packages
"""

import pandas as pd
import seaborn as sns
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from scipy.stats import shapiro
import plotly.express as px

!pip install streamlit
import streamlit as st

"""## **DATA**

### **Provinsi**

#### **JKT**
"""

jkt_tb = pd.read_csv('TB_DKI_Jakarta.csv')

jkt_tb1 = jkt_tb.drop(labels=['Puskesmas', 'Penderita_Laki','Penderita_Perempuan'], axis=1)
jkt_tb1 = jkt_tb1.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','Total_Penderita':'Jumlah Penderita TB'})

jkt_dm = pd.read_csv('DM_DKI_Jakarta.csv')

jkt_dm1 = jkt_dm.drop(labels=['Puskesmas'], axis=1)
jkt_dm1 = jkt_dm1.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','Jumlah_Penderita_DM':'Jumlah Penderita DM'})

jkt_data = pd.merge(jkt_tb1,jkt_dm1)
jkt_data

"""**DIY**"""

diy_data = pd.read_csv('DI_Yogya.csv', sep=';')
diy_data = diy_data.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','TB':'Jumlah Penderita TB','DM':'Jumlah Penderita DM'})
diy_data

"""**BANTEN**"""

banten_dm = pd.read_csv('DM_Banten.csv', sep=',')
banten_dm = banten_dm.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','Jumlah_Penderita_DM':'Jumlah Penderita DM'})
banten_dm = banten_dm.drop(labels=['Puskesmas'], axis=1)

banten_tb = pd.read_csv('TB_Banten.csv', sep=',')
banten_tb = banten_tb.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','Total_Penderita':'Jumlah Penderita TB'})
banten_tb = banten_tb.drop(labels=['Puskesmas','Penderita_Laki','Penderita_Perempuan'], axis=1)

banten_data = pd.merge(banten_tb,banten_dm)
banten_data

"""**JABAR**"""

jabar_dm = pd.read_csv('DM_Jawa_Barat.csv', sep=';')
jabar_dm = jabar_dm.rename(columns={'Kecamatan_Kota':'Kabupaten/Kota','Jumlah_Penderita_DM':'Jumlah Penderita DM'})

jabar_tb = pd.read_csv('TB_Jawa_Barat.csv', sep=';')
jabar_tb = jabar_tb.rename(columns={'Kecamatan_Kota':'Kabupaten/Kota','Total_Penderita':'Jumlah Penderita TB'})
jabar_tb = jabar_tb.drop(labels=['Penderita_Laki','Penderita_Perempuan'], axis=1)

jabar_data = pd.merge(jabar_tb,jabar_dm)
jabar_data

"""**JATIM**"""

jatim_data = pd.read_csv('Jawa_Timur.csv', sep=';')
jatim_data = jatim_data.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','TB':'Jumlah Penderita TB','DM':'Jumlah Penderita DM'})
jatim_data

"""**JATENG**"""

jateng_data = pd.read_csv('Jawa_Tengah.csv', sep=';')
jateng_data = jateng_data.rename(columns={'Kabupaten_Kota':'Kabupaten/Kota','TB':'Jumlah Penderita TB','DM':'Jumlah Penderita DM'})
jateng_data

"""### **Merged**"""

jawa_1 = jkt_data.append(diy_data)
jawa_2 = jawa_1.append(banten_data)
jawa_3 = jawa_2.append(jabar_data)
jawa_4 = jawa_3.append(jateng_data)
jawa_data = jawa_4.append(jatim_data)
jawa_data

"""### **Info**"""

jawa_data.info()

"""### **Quality Check**"""

jawa_data.isnull().sum()

"""### **Descriptive Stat**"""

jawa_data.describe(include='number')

jawa_data.describe(include='object')

"""### **Correlation**"""

jawa_data.corr()

"""### **Top Metrics**"""

# Total TB
sum_TB = jawa_data['Jumlah Penderita TB'].sum()
sum_TB

# Total DM
sum_DM = jawa_data['Jumlah Penderita DM'].sum()
sum_DM

"""## Visualization"""

jawa_data.groupby(['Kabupaten/Kota']).sum().reset_index()

"""### **BAR**"""

import pandas as pd
import matplotlib.pyplot as mp
 
# take data
datajkt = jkt_data
 
 
df = pd.DataFrame(datajkt, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(10, 10))
 
# print bar graph
mp.show()

# take data
databanten = banten_data
 
df = pd.DataFrame(databanten, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(10, 10))
 
# print bar graph
mp.show()

# take data
datadiy = diy_data
 
 
df = pd.DataFrame(datadiy, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(10, 10))
 
# print bar graph
mp.show()

# take data
datajabar = jabar_data
 
 
df = pd.DataFrame(datajabar, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(20, 10))
 
# print bar graph
mp.show()

# take data
datajateng = jateng_data
 
 
df = pd.DataFrame(datajateng, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(15, 10))
 
# print bar graph
mp.show()

# take data
datajatim = jatim_data
 
 
df = pd.DataFrame(datajatim, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(20, 10))
 
# print bar graph
mp.show()

# take data
barjawa = datajawa
 
df = pd.DataFrame(datajawa, columns=["Provinsi", "Penderita TB", "Penderita DM"])
 
# plot the dataframe
df.plot(x="Provinsi", y=["Penderita TB", "Penderita DM"], kind="bar", figsize=(10, 5))
 
# print bar graph
mp.show()

"""### **SCATTER**"""

pip install tabulate

from tabulate import tabulate

# JKT
sum_dm_jkt = jkt_data['Jumlah Penderita DM'].sum()
sum_tb_jkt = jkt_data['Jumlah Penderita TB'].sum()

# Banten
sum_dm_btn = banten_data['Jumlah Penderita DM'].sum()
sum_tb_btn = banten_data['Jumlah Penderita TB'].sum()

# DIY
sum_dm_diy = diy_data['Jumlah Penderita DM'].sum()
sum_tb_diy = diy_data['Jumlah Penderita TB'].sum()

# Jabar
sum_dm_jabar = jabar_data['Jumlah Penderita DM'].sum()
sum_tb_jabar = jabar_data['Jumlah Penderita TB'].sum()

# Jateng
sum_dm_jateng = jateng_data['Jumlah Penderita DM'].sum()
sum_tb_jateng = jateng_data['Jumlah Penderita TB'].sum()

# Jatim
sum_dm_jatim = jatim_data['Jumlah Penderita DM'].sum()
sum_tb_jatim = jatim_data['Jumlah Penderita TB'].sum()

sum_dm_jabar

datajawa1 = [ 
    ['DKI Jakarta', sum_tb_jkt, sum_dm_jkt], 
    ['Banten', sum_tb_btn, sum_dm_btn], 
    ['DI Yogyakarta', sum_tb_diy, sum_dm_diy],
    ['Jawa Barat', sum_tb_jabar, sum_dm_jabar],
    ['Jawa Tengah', sum_tb_jateng, sum_dm_jateng],
    ['Jawa Timur', sum_tb_jatim, sum_dm_jatim]]
head = ['Provinsi', 'Penderita TB', 'Penderita DM']

print(tabulate(datajawa1, headers=['Provinsi', 'Penderita TB', 'Penderita DM'], tablefmt="grid"))

datajawa = {'Provinsi':['DKI Jakarta','Banten','DI Yogyakarta','Jawa Barat','Jawa Tengah','Jawa Timur'], 'Penderita Tuberkulosis':[sum_tb_jkt,sum_tb_btn,sum_tb_diy,sum_tb_jabar,sum_tb_jateng,sum_tb_jatim], 'Penderita Diabetes':[sum_dm_jkt,sum_dm_btn,sum_dm_diy,sum_dm_jabar,sum_dm_jateng,sum_dm_jatim]}
print(tabulate(datajawa, headers='keys'))

# take data
datajawa = jawa_data
 
x = [1, 2, 3, 4]
y = [4, 1, 3, 6]
plt.scatter(x, y, c='green')

x = [5, 6, 7, 8]
y = [1, 3, 5, 2]
plt.scatter(x, y, c='red')


df = pd.DataFrame(datajawa, columns=["Kabupaten/Kota", "Jumlah Penderita TB", "Jumlah Penderita DM"])
 
# plot the dataframe
df.plot(x="Kabupaten/Kota", y=["Jumlah Penderita TB", "Jumlah Penderita DM"], kind="bar", figsize=(10, 10))
 
# print bar graph
mp.show()

from matplotlib import pyplot as plt
from matplotlib.pyplot import figure

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
prov = datajawa['Provinsi']
tb = [sum_tb_jkt,sum_tb_btn,sum_tb_diy,sum_tb_jabar,sum_tb_jateng,sum_tb_jatim]
dm = [sum_dm_jkt,sum_dm_btn,sum_dm_diy,sum_dm_jabar,sum_dm_jateng,sum_dm_jatim]

# hubungan tugas dengan uts
ax.scatter(prov,tb,color='red')
# hubungan tugas dengan uas
ax.scatter(prov,dm,color='green')

# set label X dan Y
ax.set_xlabel('Provinsi')
ax.set_ylabel('Jumlah')
ax.set_title('Prevalensi Diabetes terhadap TBC')

# tampilkan
plt.show()

"""## **STREAMLIT**

### INSTALL
"""

!pip install streamlit
!pip install pyngrok

from pyngrok import ngrok

# [<NgrokTunnel: "http://<public_sub>.ngrok.io" -> "http://localhost:80">]
tunnels = ngrok.get_tunnels()

pip install streamlit